# Generated by Django 3.2.6 on 2024-05-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='destination',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='source',
            new_name='user',
        ),
    ]
